//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SveynayaFabrica.data.migrations
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapRule
    {
        public int Id { get; set; }
        public string IdMaterial { get; set; }
        public int IdUnit { get; set; }
        public int Value { get; set; }
    
        public virtual Fabric Fabric { get; set; }
    }
}
